### ISSUE TITLE
Johnny-Five Compatibility

### ISSUE THREAD

**Issue by connerbrooks** [ms-iot/node-wiring#3]
This modules should be a compatible [io plugin](https://github.com/rwaldron/johnny-five/wiki/IO-Plugins) for [Johnny-Five](https://github.com/rwaldron/johnny-five).

**Comment by ooeygui** [comment]
We would gladly accept contributions to enable compatibility. I've added a help request for this https://github.com/ms-iot/node-wiring/issues/11
